AllCops:
  TargetRubyVersion: 2.6.3
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 100